release:
  # If set to auto, will mark the release as not ready for production in case there is an indicator for this in the
  # tag e.g. v1.0.0-rc1 .If set to true, will mark the release as not ready for production.
  prerelease: auto

  # If set to true, will not auto-publish the release. This is done to allow us to review the changelog before publishing.
  draft: false

builds:
  - binary: dockvisor
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

brews:
  - repository:
      owner: khulnasoft
      name: homebrew-dockvisor
      token: "{{.Env.TAP_GITHUB_TOKEN}}"
    homepage: "https://github.com/khulnasoft/dockvisor/"
    description: "A tool for exploring layers in a docker image"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: MIT
    maintainer: Alex Goodman
    homepage: https://github.com/khulnasoft/dockvisor/
    description: "A tool for exploring layers in a docker image"
    formats:
      - rpm
      - deb

dockers:
  -
    ids:
      - dockvisor
    dockerfile: Dockerfile
    # todo: on 1.0 remove 'v' prefix
    image_templates:
      - "khulnasoft/dockvisor:latest"
      - "khulnasoft/dockvisor:{{ .Tag }}"
      - "khulnasoft/dockvisor:v{{ .Major }}"
      - "khulnasoft/dockvisor:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--build-arg=DOCKER_CLI_VERSION={{.Env.DOCKER_CLI_VERSION}}"
